name: Build and test pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env
          echo 'MONGODB_URI: ${{ secrets.MONGODB_URI }}' >> .env
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      # Run all unit and integration tests
      - run: npm test
      # Run end-to-end tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          headed: true
          wait-on: http://localhost:3000