name: Build and test pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run build --if-present
      - name: Run unit and integration tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm test
      - name: Run e2e tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          headed: true
          wait-on: http://localhost:3000